# Generated by Django 5.0 on 2024-01-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_phone', models.CharField(max_length=50)),
                ('user_dob', models.DateField(max_length=100)),
            ],
        ),
    ]
