# Generated by Django 5.0 on 2024-01-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_products_product_id_alter_register_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='updated_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
